#server:
#  port: 1125
#
#spring:
#  datasource:
#    url: jdbc:mysql:///mod
#    username: root
#    password: xsy021125
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#mybatis:
#  mapper-locations:
#  type-aliases-package: